services:
    db:
        image: postgres:15-alpine
        restart: always
        env_file:
            - .env.dev
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        env_file:
            - .env.dev
        restart: always
        environment:
            TZ: Asia/Bangkok
            DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-nahi_clinic}?schema=public
            NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
            NEXTAUTH_TRUST_HOST: "true"
        ports:
            - "3000:3000"
        depends_on:
            - db

volumes:
    postgres_data:
